/* Koolituse küsimuste pank (dokument „Pidurdusmaa koolitus — küsimustik“, 2026-10-07).
 * Arvud: sama mudel mis kalkulaator — VW Golf 8, keskmine C-klassi rehv, reaktsioon 1 s,
 * kuiv +15 °C, märg 1 mm vett +10 °C, lumi ja jää −5 °C (vt dokumenti).
 *
 * Üks küsimus: { id, teema, m, k, v, o, s, sim? }
 *   m = märgid: 'e' sobib eeltesti, 'j' järeltesti, 't' trikk (täpne lugemine)
 *   k = küsimus, v = 4 vastust, o = õige vastuse indeks (0–3), s = selgitus
 *   sim = [nimi, aadress] — „Proovi simulaatoris“ (olukord aadressis)
 */

export const TEEMAD = [
	['kiirus', 'Kiirus ja pidurdusteekond'],
	['reaktsioon', 'Reaktsiooniaeg ja tähelepanu'],
	['teeolud', 'Teeolud: märg, lumi, jää'],
	['rehvid', 'Rehvid'],
	['pikivahe', 'Pikivahe'],
	['pimedus', 'Pimedus ja nähtavus'],
	['kurvid', 'Kurvid'],
	['koorem', 'Koorem ja haagis'],
	['reeglid', 'Eesti reeglid']
];

/* simulaatori aadressid (olukord räsis, nagu jagamislinkidel) */
const KUIV = 'vesi=0&temp=15';
const LUMI = 'pind=SNOW_PACKED&vesi=0&temp=-5&kat=WINTER_NORDIC';
const JAA = 'pind=ICE&vesi=0&temp=-5&kat=WINTER_NORDIC';
/* auto = VW Golf 8, sama mis küsimuste arvudes (muidu näitaks simulaator üldist kompaktautot) */
const GOLF = 'mk=Volkswagen&md=Golf&veh=vw_golf_8&';
const pk = (a, b) => '/liiklusohutus/#' + GOLF + a + (b ? '&b=1&' + (GOLF + b).split('&').map((x) => 'b.' + x).join('&') : '');
const SIM = {
	peatumine: (a, b) => ['Peatumisteekond', pk(a, b)],
	pimedas: (q) => ['Nähtavus pimedas', '/liiklusohutus/pimedas/#' + q],
	pikivahe: (q) => ['Pikivahe', '/liiklusohutus/pikivahe/' + (q ? '#' + q : '')],
	kurv: (q) => ['Kurv ja rehvid', '/liiklusohutus/kurv/' + (q ? '#' + q : '')],
	/* mäng samas olukorras: m = tuled (eesolev auto) | pime (jalakäija); q = kiirus, ilm, riie, vahe, mm */
	mang: (m, q) => ['Reaktsioonimäng', '/liiklusohutus/reaktsioon/' + (m ? '?m=' + m + (q ? '&' + q : '') : '')],
	vanus: ['Rehvi vanus (DOT)', '/rehvi-vanus/'],
	kalkulaator: ['Kalkulaator: rehvide võrdlus', '/']
};

const K = [
	/* ---------- 1. kiirus ---------- */
	['kiirus', 'e', 'Kiirus kasvab 50-lt 100 km/h peale. Kuidas muutub pidurdusteekond kuival teel (pidurdamise algusest)?',
		['Kaks korda pikem', 'Kolm korda pikem', 'Umbes neli korda pikem', 'Ei muutu, ABS hoiab selle samana'], 2,
		'Liikumisenergia kasvab kiiruse ruuduga. Mudelis 9,6 m → 36,6 m.', SIM.peatumine(KUIV + '&kiirus=50', KUIV + '&kiirus=100')],
	['kiirus', 'e', 'Mis on „peatumisteekond“?',
		['Teekond pidurdamise algusest seisuni', 'Reaktsiooniaja teekond + pidurdusteekond', 'Ainult reaktsiooniaja teekond', 'Teekond, mille auto läbib 1 sekundiga'], 1,
		'Enne pidurdamist sõidab auto reaktsiooniaja jooksul täiskiirusel edasi. 50 km/h ja 1 s = 13,9 m enne, kui pidur üldse hakkab.'],
	['kiirus', 'e', 'Kui pikk on peatumisteekond 50 km/h pealt kuival teel, kui reageerid 1 sekundiga?',
		['Umbes 10 m', 'Umbes 15 m', 'Umbes 24 m', 'Umbes 40 m'], 2,
		'13,9 m reaktsioon + 9,6 m pidurdus = 23,5 m. Pool sellest on reaktsioon.', SIM.mang('tuled', 'kiirus=50&ilm=kuiv')],
	['kiirus', 'jt', 'Sinu ees sõitev auto sõidab 50 km/h, sina 60 km/h. Mõlemad näevad sama takistust ja pidurdavad. Kui tema seisab, mis kiirusega oled sina samas kohas?',
		['Ka seisad', 'Umbes 10 km/h', 'Umbes 25 km/h', 'Umbes 45 km/h'], 3,
		'Lisakiirus „sööb“ pidurdusteekonna lõpu, kus auto oleks muidu juba aeglane. Kuival teel 1 s reaktsiooniga on 60 km/h auto seal veel 45 km/h.', SIM.peatumine(KUIV + '&kiirus=50', KUIV + '&kiirus=60')],
	['kiirus', 'j', '50 km/h alas, märg tee. Üks auto sõidab 50 km/h, teine 70 km/h. Kohas, kus esimene jõuab seisma, sõidab teine veel…',
		['10 km/h', '30 km/h', '61 km/h', '70 km/h'], 2,
		'70 km/h juures läbib reaktsioon 19,4 m ja pidurdus on alles alanud.', SIM.peatumine('kiirus=50', 'kiirus=70')],
	['kiirus', 'e', 'Kas ABS lühendab pidurdusteekonda?',
		['Jah, alati poole võrra', 'Ei pruugi; ABS hoiab rattad pöörlemas, et saaksid pidurdades juhtida', 'Ainult kuival teel', 'Ei, ABS pikendab alati'], 1,
		'ABS-i põhiväärtus on juhitavus. Asfaldil on teekond enamasti sama või lühem, lahtisel lumel võib lukus ratas peatuda isegi lühemalt.'],
	['kiirus', 'e', '90 km/h pealt märjal teel: kui pikk on pidurdusteekond (pidurdamise algusest)?',
		['Umbes 20 m', 'Umbes 30 m', 'Umbes 45 m', 'Umbes 80 m'], 2,
		'Mudelis 44,8 m, kuival 29,8 m. Lisa 25 m reaktsiooni ja peatumisteekond on ligi 70 m.', SIM.mang('tuled', 'kiirus=90&ilm=vihm')],
	['kiirus', 'jt', 'Mitu protsenti pikem on pidurdusteekond 110 km/h pealt võrreldes 90 km/h-ga (kuiv)?',
		['22% (sama palju kui kiirus)', 'Umbes 50%', 'Umbes 100%', 'Umbes 200%'], 1,
		'Kiirus +22%, aga pidurdus 29,8 m → 44,2 m ehk +48%.', SIM.peatumine(KUIV + '&kiirus=90', KUIV + '&kiirus=110')],
	['kiirus', 'jt', 'Mis on pidurdusteekonnale kõige väiksema mõjuga?',
		['Kiirus', 'Teeolud', '300 kg koormat autos', 'Rehvide muster'], 2,
		'Raskem auto vajab rohkem pidurdusjõudu, aga rehv suudab ka rohkem haarata. Mudelis 90 km/h kuival 29,8 m → 30,2 m.'],
	['kiirus', 'j', 'Allamägi 6% kaldega, märg tee, 90 km/h. Kuidas muutub pidurdusteekond võrreldes tasase teega?',
		['Ei muutu', 'Pikeneb umbes 4 m', 'Pikeneb kaks korda', 'Lüheneb'], 1,
		'Raskusjõud tõmbab autot edasi. Mudelis 44,8 m → 48,8 m; tõusul 41,5 m.', SIM.peatumine('kiirus=90', 'kiirus=90&kalle=-6')],

	/* ---------- 2. reaktsioon ---------- */
	['reaktsioon', 'e', 'Kui palju sõidab auto 90 km/h juures 1 sekundiga?',
		['9 m', '15 m', '25 m', '90 m'], 2,
		'90 km/h = 25 m/s. Kiirus jagatud 3,6-ga annab meetrid sekundis.'],
	['reaktsioon', 'e', 'Milline on tavaline reaktsiooniaeg ootamatu ohu korral liikluses?',
		['0,2 s', 'Umbes 1 s, väsinult või segatult 1,5–2 s ja rohkem', '3–4 s', 'Reaktsiooniaeg ei sõltu olukorrast'], 1,
		'Testis, kus tead, et oht tuleb, on aeg lühem. Liikluses lisandub märkamine ja otsustamine.', SIM.mang()],
	['reaktsioon', 'e', 'Vaatad telefoni 2 sekundit, kiirus 50 km/h. Kui palju sõidad pimesi?',
		['Umbes 5 m', 'Umbes 14 m', 'Umbes 28 m', 'Umbes 50 m'], 2,
		'13,9 m/s × 2 s. See on rohkem kui terve peatumisteekond märjal teel 1 s reaktsiooniga (27,4 m).', SIM.peatumine('kiirus=50', 'kiirus=50&reakt=2')],
	['reaktsioon', 'jt', 'Märg tee, 50 km/h, takistus 27 m ees. Reageerid 1 s ja jõuad peatuda. Mis juhtub, kui vaatasid just telefoni ja reageerid 2 s?',
		['Peatud 5 m varem', 'Peatud napilt', 'Sõidad takistusele otsa peaaegu täiskiirusel', 'Midagi ei muutu, pidurid on samad'], 2,
		'2 sekundiga läbid juba 27,8 m. Pidur ei jõua tööle hakatagi.', SIM.peatumine('kiirus=50&reakt=2')],
	['reaktsioon', 'e', 'Mis lühendab reaktsiooniaega kõige rohkem?',
		['Võimsam auto', 'Kõrgem istumisasend', 'Ette vaatamine ja jalg valmis pedaali kohal, kui olukord on kahtlane', 'Kiirem sõit, et ohust kiiremini mööda saada'], 2,
		'Kui oht on juba arvestatud, jääb ära otsustamise aeg.'],
	['reaktsioon', 'jt', 'Kas 1 s pikem reaktsioon lisab 50 km/h ja 100 km/h juures sama palju meetreid?',
		['Jah, 1 s on 1 s', 'Ei, 100 km/h juures kaks korda rohkem', 'Ei, 100 km/h juures neli korda rohkem', 'Ei, 50 km/h juures rohkem'], 1,
		'Reaktsiooni teekond kasvab kiirusega otse (13,9 m vs 27,8 m), pidurdusteekond kiiruse ruuduga.'],
	['reaktsioon', 'j', 'Väsinud juht reageerib 0,5 s aeglasemalt. Kui palju lisab see 90 km/h juures?',
		['Umbes 2 m', 'Umbes 6 m', 'Umbes 12–13 m', 'Umbes 25 m'], 2,
		'25 m/s × 0,5 s = 12,5 m. See on umbes kolme auto pikkus.'],
	['reaktsioon', 'jt', 'Reaktsioonimängus said 0,4 s. Mida see tähendab liikluse kohta?',
		['Sinu peatumisteekond on alati selline', 'Liikluses on see tavaliselt pikem, sest sa ei tea, millal oht tuleb', 'Liikluses on see lühem, sest oled seal tähelepanelikum', 'Reaktsioonil pole liikluses tähtsust, ABS teeb töö'], 1,
		'Mängus ootad ohtu. Liikluses tuleb oht märgata, ära tunda ja otsustada.', SIM.mang()],
	['reaktsioon', 'e', 'Mis on raadio sättimise, kõrvalistujaga vestluse ja telefoni lugemise ühine oht?',
		['Need on kõik keelatud', 'Need viivad pilgu või tähelepanu teelt ja pikendavad reaktsiooni', 'Need väsitavad silmi', 'Ühist ohtu pole'], 1,
		'Telefoni lugemine viib pilgu teelt, mõttega mujal olek pikendab märkamist ka siis, kui silmad on teel.'],

	/* ---------- 3. teeolud ---------- */
	['teeolud', 'e', '50 km/h, talverehvid. Mitu korda pikem on pidurdusteekond tallatud lumel võrreldes kuiva asfaldiga (suverehviga)?',
		['Sama', 'Umbes 1,5 korda', 'Umbes 3 korda', 'Umbes 10 korda'], 2,
		'Kuival 9,6 m, lumel talverehviga 26,2 m.', SIM.peatumine(KUIV + '&kiirus=50', LUMI + '&kiirus=50')],
	['teeolud', 'e', '50 km/h, jää, Põhjamaade lamellrehv. Kui pikk on pidurdusteekond?',
		['Umbes 10 m', 'Umbes 20 m', 'Umbes 40 m', 'Umbes 100 m'], 2,
		'Mudelis 38,9 m, ehk ligi neli korda kuiva asfaldi pikkus.', SIM.peatumine(JAA + '&kiirus=50')],
	['teeolud', 'et', 'Millal on jää kõige libedam?',
		['Kõvas külmas, −15 °C', 'Nulli lähedal, kui jää pinnal on õhuke veekiht', 'Temperatuur ei mõjuta', 'Ainult öösel'], 1,
		'Mudelis lamellrehvi pidurdusteekond 50 km/h pealt: −15 °C 27,4 m, −5 °C 38,9 m, 0 °C 58,6 m.', SIM.peatumine('pind=ICE&vesi=0&temp=-15&kat=WINTER_NORDIC&kiirus=50', 'pind=ICE&vesi=0&temp=0&kat=WINTER_NORDIC&kiirus=50')],
	['teeolud', 'jt', 'Termomeeter näitab +2 °C. Kas tee võib olla jäine?',
		['Ei, jää tekib alles alla 0 °C', 'Jah: sillad, varjus lõigud ja teepind võivad olla õhust külmemad', 'Ainult siis, kui sajab lund', 'Ainult kruusateel'], 1,
		'Auto termomeeter mõõdab õhku. Sild jahtub ka alt ning varjus olev lõik ei saa päikest.'],
	['teeolud', 'e', 'Mis on vesiliug?',
		['Libisemine märjal teekattemärgistusel', 'Rehv tõuseb veekihi peale ega puutu enam teed', 'Vesi pidurikettal', 'Libisemine sulavas lumes'], 1,
		'Kui muster ei jõua vett eest ära juhtida, jääb rehvi ja tee vahele vesi. Pidurid ja rool ei mõju.'],
	['teeolud', 'j', '90 km/h, 3 mm veekiht (sademevesi roopas). Kui palju pikeneb pidurdusteekond, kui rehvi muster on uue 8 mm asemel 1,6 mm?',
		['Paar meetrit', 'Umbes 10 m', 'Peaaegu kaks korda: 54 m → 101 m', 'Ei pikene, vesi on mõlemale sama'], 2,
		'Õhukese mustriga hakkab rehv osaliselt vee peal libisema.', SIM.peatumine('kiirus=90&vesi=3', 'kiirus=90&vesi=3&muster=1.6')],
	['teeolud', 'e', 'Mida teha, kui tunned vesiliugu (rool läheb kergeks)?',
		['Pidurda kõvasti', 'Keera rooli järsult', 'Võta gaas ära, hoia rool otse ja oota, kuni rehvid haarduvad', 'Lisa gaasi'], 2,
		'Järsk pidurdus või rool ajal, kui rehv ei haaku, võib auto haarde tagasi tulles külje peale visata.'],
	['teeolud', 'j', 'Lahtine lumi või tallatud lumi: kus on pidurdusteekond pikem?',
		['Tallatud lumel', 'Lahtisel lumel', 'Sama', 'Sõltub ainult kiirusest'], 1,
		'Mudelis 50 km/h pealt 26,2 m tallatud ja 30,4 m lahtisel lumel.', SIM.peatumine(LUMI + '&kiirus=50', 'pind=SNOW_LOOSE&vesi=0&temp=-5&kat=WINTER_NORDIC&kiirus=50')],
	['teeolud', 'jt', 'Märg asfalt, 90 km/h. Suverehviga 44,8 m. Talverehviga…',
		['Lühem, talverehv haarab alati paremini', 'Pikem, umbes 47,5 m', 'Täpselt sama', 'Kaks korda pikem'], 1,
		'Talverehv on tehtud lume ja jää jaoks. Märjal ja kuival asfaldil on suverehv parem.', SIM.peatumine('kiirus=90', 'kiirus=90&kat=WINTER_NORDIC')],
	['teeolud', 'j', 'Esimene vihm pärast pikka kuiva perioodi. Miks on tee eriti libe?',
		['Vesi on külm', 'Teele kogunenud tolm, kummipuru ja õli segunevad veega õliseks kihiks', 'Vihm on soolane', 'Ei ole libedam kui tavaliselt'], 1,
		'See kiht uhutakse ära alles pikema vihmaga.'],

	/* ---------- 4. rehvid ---------- */
	['rehvid', 'e', '50 km/h tallatud lumel. Suverehviga on pidurdusteekond…',
		['Sama kui talverehviga', 'Umbes 10% pikem', 'Umbes kaks korda pikem', 'Ligi 2,5 korda pikem: 26 m → 61 m'], 3,
		'Suverehvi kumm kõvastub külmaga ja muster ei haara lund. Jääl on vahe veel suurem: 39 m → 83 m.', SIM.peatumine(LUMI + '&kiirus=50', 'pind=SNOW_PACKED&vesi=0&temp=-5&kat=SUMMER_TOURING&kiirus=50')],
	['rehvid', 'et', 'Kas talverehv pidurdab suvel kuival asfaldil sama hästi kui suverehv?',
		['Jah, talverehv haarab alati paremini', 'Ei, pidurdusteekond on pikem: 50 km/h pealt 9,6 m → 12,7 m', 'Vahet pole', 'Talverehv on suvel isegi parem'], 1,
		'Pehme kumm ja lamellid painduvad soojas asfaldil.', SIM.peatumine(KUIV + '&kiirus=50', KUIV + '&kiirus=50&kat=WINTER_NORDIC')],
	['rehvid', 'e', 'Suverehvi seaduslik miinimummuster on 1,6 mm. Kui palju pikeneb pidurdusteekond märjal teel 90 km/h pealt võrreldes uue rehviga?',
		['Ei pikene, seadus lubab', 'Umbes 6 m: 44,8 m → 51,0 m', 'Umbes 30 m', 'Kaks korda'], 1,
		'Seaduslik ei tähenda ohutu. Sademevee roopas on vahe palju suurem.', SIM.peatumine('kiirus=90', 'kiirus=90&muster=1.6')],
	['rehvid', 'e', 'Talverehvi muster 3 mm. Kui palju pikem on pidurdusteekond lumel 50 km/h pealt võrreldes uuega (8 mm)?',
		['Ei muutu', 'Umbes veerandi võrra: 26,2 m → 32,7 m', 'Kaks korda', 'Natuke lühem'], 1,
		'Lumel haarab muster ise lund. Mida madalam muster, seda vähem haaret.', SIM.mang('tuled', 'kiirus=50&ilm=talv&mm=3')],
	['rehvid', 'j', 'Rehv on 10 aastat vana, aga muster täis. Mis juhtub pidurdusteekonnaga märjal teel 90 km/h pealt?',
		['Ei muutu, muster on tähtsam', 'Pikeneb umbes 2 m, sest kumm kõvastub vanusega', 'Pikeneb kaks korda', 'Lüheneb'], 1,
		'Mudelis 44,8 m → 47,2 m. Vanuse mõju on väiksem kui mustri mõju, aga see on olemas.', SIM.vanus],
	['rehvid', 'e', 'Kust saad teada rehvi vanuse?',
		['Rehvi laiusest', 'DOT-koodi neljast viimasest numbrist: nädal ja aasta (nt 2321 = 23. nädal 2021)', 'Rehvimõõdust', 'Seda ei saa teada'], 1,
		'Number on rehvi küljel ovaalse raami sees.', SIM.vanus],
	['rehvid', 'e', 'EL rehvimärgisel on märghaarde klass A–E. Kui palju erineb pidurdusteekond märjal 90 km/h pealt A- ja E-klassi suverehviga?',
		['Alla meetri', 'Umbes 5 m', 'Umbes 18 m: 41,4 m vs 59,1 m', 'Vahet pole, klass näitab kütusekulu'], 2,
		'E-klassiga oled seal, kus A-klassiga auto juba seisab, veel umbes 50 km/h kiirusega.', SIM.peatumine('kiirus=90&klass=A', 'kiirus=90&klass=E')],
	['rehvid', 'jt', 'Rehvirõhk on 0,7 bar alla soovituse. Mis juhtub märjal teel?',
		['Haare paraneb, sest kontaktpind on suurem', 'Pidurdusteekond pikeneb ja vesiliug algab madalamal kiirusel', 'Ei muutu midagi peale kütusekulu', 'Rehv kulub ainult keskelt'], 1,
		'Pehme rehv ei suru vett mustrist välja. Mudelis 90 km/h pealt 44,6 m → 46,0 m, sügavas vees palju rohkem.'],
	['rehvid', 'j', 'Sügisel läheb ilm 20 kraadi külmemaks. Mis juhtub rehvirõhuga?',
		['Ei muutu', 'Langeb umbes 0,2 bar', 'Tõuseb', 'Langeb poole võrra'], 1,
		'Külm õhk võtab vähem ruumi, umbes 0,1 bar iga 10 kraadi kohta. Kontrolli rõhku rehvivahetuse järel ja külmaga uuesti.'],
	['rehvid', 'e', 'Jää, −5 °C, 50 km/h. Naastrehv või Põhjamaade lamellrehv?',
		['Sama', 'Naastrehv peatub lühemalt: 31,4 m vs 38,9 m', 'Lamell peatub lühemalt', 'Jääl ei aita kumbki'], 1,
		'Naastude eelis on suurim nulli lähedal. Kuival ja märjal asfaldil on vahe väike.', SIM.peatumine(JAA + '&kiirus=50', 'pind=ICE&vesi=0&temp=-5&kat=WINTER_STUDDED&kiirus=50')],
	['rehvid', 'jt', 'Ilmastikurehv (all season) lumel ja jääl, 50 km/h. Mis on õige?',
		['Mõlemal sama hea kui Põhjamaade talverehv', 'Lumel peaaegu sama hea (25 m), jääl palju halvem (60 m vs 39 m)', 'Mõlemal sama halb kui suverehv', 'Jääl parem kui naastrehv'], 1,
		'Lumele sobiv muster ei tee kummist jäärehvi. Eesti talves loeb just jää.', SIM.peatumine(JAA + '&kiirus=50', 'pind=ICE&vesi=0&temp=-5&kat=ALL_SEASON&kiirus=50')],
	['rehvid', 'jt', 'Ees on uued rehvid, taga vanad. Kuhu panna paremad rehvid, kui ostad ainult kaks?',
		['Ette, sest esirattad pidurdavad rohkem', 'Taha, sest libeda tagaosaga auto läheb kurvis külg ees ümber ja seda on raske püüda', 'Vahet pole', 'Üks ette, üks taha'], 1,
		'Paremad rehvid taha on rehvitootjate tavaline soovitus ka esiveolisel autol.', SIM.kurv('kr=60~marg~SUMMER_TOURING~8~2~vw_golf_3')],

	/* ---------- 5. pikivahe ---------- */
	['pikivahe', 'e', 'Kuidas mõõta pikivahet ilma meetriteta?',
		['Auto pikkustes', 'Sekundites: kui eesolev auto möödub postist, loe „üks-tuhat, kaks-tuhat“, kuni sina jõuad postini', 'Pikivahet ei saagi mõõta', 'Spidomeetri järgi'], 1,
		'Sekundites mõõdetud vahe kasvab kiirusega ise kaasa.', SIM.mang('tuled', 'kiirus=90&vahe=2')],
	['pikivahe', 'e', 'Eesolev auto pidurdab äkki. Sina reageerid 1 s, pikivahe on 1 s. Kas jõuad peatuda, kui mõlemal on samad rehvid?',
		['Jah, alati', 'Napilt, vahe on nullilähedane', 'Ei, kunagi', 'Sõltub ainult kiirusest'], 1,
		'Mõlemad pidurdavad sama teekonna. Sinu lisateekond on ainult reaktsioon, mis sööb kogu 1 s vahe ära.', SIM.mang('tuled', 'kiirus=90&vahe=1&ilm=kuiv')],
	['pikivahe', 'jt', 'Kas libedal teel ei olegi siis pikem pikivahe vajalik, kui mõlemad pidurdavad halvemini?',
		['Pole vaja, vahe jääb samaks', 'On vaja: eesolev auto võib peatuda kiiremini (paremad rehvid, sõidab millelegi otsa), ja libedal teel on see vahe meetrites suurem', 'Pikem vahe on vaja ainult kuival', 'Libedal teel piisab 1 sekundist'], 1,
		'Halvim juhtum on see, kui eesolev auto peatub äkki. Libedal on sinu pidurdusteekond pikk ja varu kulub kiiresti.', SIM.mang('tuled', 'kiirus=70&vahe=2&ilm=talv')],
	['pikivahe', 'e', 'Mitu meetrit on 2-sekundiline pikivahe 90 km/h juures?',
		['18 m', '25 m', '50 m', '90 m'], 2,
		'25 m/s × 2 s. Linnas 50 km/h juures on sama 2 s ainult 28 m.'],
	['pikivahe', 'j', 'Telefoni pilk kestab 2 s ja pikivahe on 2 s. Mis juhtub, kui eesolev auto just siis pidurdab?',
		['Jõuad peatuda', 'Kogu varu on kulunud enne, kui üldse pidurdad: kokkupõrge', 'ABS päästab', 'Ei juhtu midagi, eesolev auto peatub aeglaselt'], 1,
		'2 s pilku + reaktsioon on pikem kui 2 s vahe.', SIM.mang('tuled', 'kiirus=90&vahe=2')],
	['pikivahe', 'j', 'Keegi kiilub sinu ette ja pikivahe väheneb poole sekundini. Mida teha?',
		['Sõita tihedalt edasi', 'Vilgutada tulesid', 'Võtta gaasi ära ja lasta vahe uuesti suureks', 'Mööda sõita'], 2,
		'Sinu vahe on sinu ohutus, ka siis, kui viga tegi teine.'],
	['pikivahe', 'jt', 'Sinu taga sõidab keegi liiga lähedal. Mis aitab kõige rohkem?',
		['Järsk pidurdus „hoiatuseks“', 'Suurendada vahet enda ees, et saaksid ise pehmemalt pidurdada', 'Kiirendada', 'Midagi ei saa teha'], 1,
		'Kui sina pead pidurdama järsult, lööb tagumine otsa. Suurem vahe ees annab aega pidurdada sujuvalt.'],
	['pikivahe', 'j', 'Kas 3 sekundit pikivahet on kiirteel liiga palju?',
		['Jah, see raiskab teed', 'Ei: 110 km/h juures on see 92 m ja annab varu ka väsimuse ning märja tee jaoks', 'Jah, seadus lubab 1 s', 'Sõltub autost'], 1,
		'30,6 m/s × 3 s = 92 m.', SIM.pikivahe('vahe=3&kiirus=110')],

	/* ---------- 6. pimedus ---------- */
	['pimedus', 'e', 'Lähitulede valgel: kui kaugelt märkab juht tumedas riietuses helkurita jalakäijat?',
		['Umbes 150 m', 'Umbes 80 m', 'Umbes 30 m', 'Umbes 10 m'], 2,
		'Helkuriga 130–150 m (Transpordiamet).', SIM.mang('pime', 'riie=tume&kiirus=50&ilm=kuiv')],
	['pimedus', 'e', 'Jalakäija on 30 m ees, tee on märg, reageerid 1 s. Mis kiiruselt jõuad veel peatuda?',
		['90 km/h', '70 km/h', 'Umbes 53 km/h', 'Umbes 20 km/h'], 2,
		'30 m kulub reaktsioonile ja pidurdusele. Kiiremini sõites jõuab auto jalakäijani veel sõites.', SIM.mang('pime', 'riie=tume&kiirus=50&ilm=vihm')],
	['pimedus', 'j', 'Pime tee, märg asfalt. Jalakäija tumedas riietuses ilmub 30 m ette, sina reageerid 1 sekundiga. Sõidad 70 km/h. Mis kiirusega jõuab auto jalakäijani?',
		['Peatub enne', 'Umbes 20 km/h', 'Umbes 57 km/h', '70 km/h'], 2,
		'1 s reaktsiooniga läbib auto 19 m ja pidurdamiseks jääb 11 m.', SIM.mang('pime', 'riie=tume&kiirus=70&ilm=vihm')],
	['pimedus', 'e', 'Kui kaugelt näeb juht lähitulede valgel helkuriga jalakäijat?',
		['30 m', '60 m', '130–150 m', '500 m'], 2,
		'Helkuriga jõuab auto peatuda ka 120–130 km/h pealt.', SIM.mang('pime', 'riie=helkur&kiirus=90&ilm=vihm')],
	['pimedus', 'e', 'Kuhu helkur riputada?',
		['Kaela, rinna kõrgusele', 'Seljakoti peale', '50–80 cm kõrgusele, sõidutee poolsele küljele', 'Mütsi peale'], 2,
		'See on autotulede kõrgus. Kaelas või rinna kõrgusel jääb helkur lähitulede koonusest välja või keha varju.'],
	['pimedus', 'jt', 'Millal on helkur seaduse järgi kohustuslik?',
		['Ainult maanteel', 'Pimeda ajal või halva nähtavuse korral', 'Ainult lastel', 'Ainult novembris'], 1,
		'Kehtib ka valgustatud teel, sest juht võib olla vastutulija tuledest pimestatud.'],
	['pimedus', 'jt', 'Heledas riietuses jalakäija: kas helkurit on vaja?',
		['Ei, hele riie on sama hea', 'Jah: hele riie paistab lähitulede valgel umbes 40–50 m, helkur 130–150 m', 'Ainult vihmaga', 'Ainult maal'], 1,
		'Helkur peegeldab valguse tagasi juhi poole, riie hajutab selle laiali.', SIM.mang('pime', 'riie=hele&kiirus=70&ilm=vihm')],
	['pimedus', 'e', 'Vastutulev auto pimestab. Kuhu vaadata?',
		['Otse tuledesse', 'Oma sõiduraja paremasse serva, ja võtta kiirus maha', 'Sulgeda hetkeks silmad', 'Panna kaugtuled peale'], 1,
		'Pimestatult ei näe sa teeäärt. Just seal võib kõndida helkurita jalakäija.'],
	['pimedus', 'j', 'Udu või tugev vihm. Mis on õige kiirus?',
		['Lubatud piirkiirus', 'Selline, et jõuad peatuda nii kaugel, kui näed', '30 km/h, alati', 'Vahet pole, kui tuled põlevad'], 1,
		'Peatumisteekond peab mahtuma nähtavuse sisse. Kui näed 40 m, peab auto 40 m sees ka seisma jääma.', SIM.peatumine('kiirus=70&takistus=40')],

	/* ---------- 7. kurvid ---------- */
	['kurvid', 'e', 'Kiirus kurvis kahekordistub. Kuidas muutub jõud, mis autot kurvist välja lükkab?',
		['Kaks korda suuremaks', 'Neli korda suuremaks', 'Ei muutu', 'Pool väiksemaks'], 1,
		'Külgjõud kasvab kiiruse ruuduga, nagu pidurdusteekondki.', SIM.kurv()],
	['kurvid', 'e', '100 m raadiusega kurv. Kuival asfaldil on piirkiirus umbes 120 km/h. Mis on see jääl (Põhjamaade lamellrehviga)?',
		['Umbes 110 km/h', 'Umbes 90 km/h', 'Umbes 55 km/h', 'Umbes 20 km/h'], 2,
		'Haare on jääl umbes viiendik kuivast. Piirkiirus kasvab haarde ruutjuurega, seega jääb alles umbes pool.', SIM.kurv('kr=50~jaa~WINTER_NORDIC~8~8~vw_passat_b8')],
	['kurvid', 'jt', 'Kas kurvis on ohutu äkitselt pidurdada, kui kiirus on piirkiirusest veidi madalam?',
		['Jah, pidurdus alati aitab', 'Ei pruugi: pidurdus kulutab sama haaret, mida pööramine vajab, ja auto võib kurvist välja kanduda', 'Jah, kui autol on ABS', 'Ainult jääl on probleem'], 1,
		'Haaret on üks „kott“. Kurvi äärel pööramiseks kulub juba peaaegu kõik.', SIM.kurv()],
	['kurvid', 'e', 'Kus on kurvis kõige õigem kiirust maha võtta?',
		['Kurvi keskel', 'Enne kurvi, otse sõites', 'Kurvist väljudes', 'Vahet pole'], 1,
		'Otse sõites saab kogu haarde pidurdamiseks kasutada.'],
	['kurvid', 'j', 'Mis on kõige ohtlikum kurvis pidurdamise juures ilma ABS-ita?',
		['Pidurid kuumenevad', 'Lukus esirattad: auto sõidab otse, kuigi rool on keeratud', 'Mootor seiskub', 'Ohtu pole'], 1,
		'Libisev ratas ei juhi. ABS hoiab rattad pöörlemas, et rool mõjuks.'],
	['kurvid', 'jt', 'Kulunud tagarehvid, head esirehvid. Mis juhtub märjas kurvis?',
		['Auto sõidab otse', 'Tagaosa võib välja libiseda ja auto keerata ümber', 'Mitte midagi, esiratastel on haare', 'Auto võtab ise kiirust maha'], 1,
		'Seepärast pannakse paremad rehvid taha.', SIM.kurv('kr=60~marg~SUMMER_TOURING~8~2~vw_golf_3')],
	['kurvid', 'j', '100 m raadiusega kurv, märg asfalt. Umbes mis on piirkiirus?',
		['Umbes 60 km/h', 'Umbes 100 km/h', 'Umbes 140 km/h', 'Sama mis kuival'], 1,
		'Märjal on haaret umbes kaks kolmandikku kuivast, piirkiirus langeb 120-lt umbes 100-le. Kulunud rehviga vähem.'],
	['kurvid', 'j', 'Kurvi lõpus on varjus jäälõik, mida sa ei näe. Mis aitab?',
		['Kiirendada, et sellest kiiresti üle saada', 'Sõita kurvi nii, et kiirusest jääb varu ka halvemaks teeks, kui näed', 'Pidurdada jää peal', 'Midagi ei aita'], 1,
		'Kurvi varu on kiirus, mille võrra oled piirkiirusest aeglasem.'],

	/* ---------- 8. koorem ja haagis ---------- */
	['koorem', 'et', 'Neli inimest ja pagas (375 kg) autos. Kui palju pikeneb pidurdusteekond märjal 80 km/h pealt?',
		['Poole võrra', 'Umbes 10 m', 'Alla meetri: 35,0 m → 35,5 m', 'Kaks korda'], 2,
		'Raskem auto surub rehvid tugevamalt vastu teed. Koorem muudab rohkem juhitavust kurvis.', SIM.peatumine('kiirus=80', 'kiirus=80&laad=375')],
	['koorem', 'e', 'Golfi taha 750 kg pidurita haagis. Kui pikk on pidurdusteekond märjal 80 km/h pealt?',
		['Sama, 35 m', 'Umbes 38 m', 'Umbes 52 m', 'Umbes 100 m'], 2,
		'Auto pidurid peavad peatama ka haagise, mis lükkab tagant.', SIM.peatumine('kiirus=80', 'kiirus=80&haagis=pidurita&haagisKg=750')],
	['koorem', 'jt', 'Kumb peatub lühemalt: 750 kg pidurita haagis või 1300 kg oma pidurite haagis?',
		['750 kg, sest on kergem', '1300 kg piduriga: 41,2 m vs 52,4 m', 'Sama', 'Sõltub ainult autost'], 1,
		'Piduriga haagis pidurdab ise. Oluline on, kas pidurid töötavad: töötamata piduritega 65,0 m.', SIM.peatumine('kiirus=80&haagis=pidurita&haagisKg=750', 'kiirus=80&haagis=piduriga&haagisKg=1300')],
	['koorem', 'e', 'Mitu kilo võib haagis kaaluda ilma oma piduriteta?',
		['300 kg', '750 kg täismassiga', '1500 kg', 'Piirang puudub'], 1,
		'Täismass tähendab haagist koos koormaga.'],
	['koorem', 'j', 'Kas raskema auto taga on sama haagis ohutum?',
		['Ei, vahet pole', 'Jah: sama haagis on raskema auto massist väiksem osa. RAV4 + 750 kg 49,5 m, Golf + 750 kg 52,4 m', 'Raskem auto on alati ohtlikum', 'Ainult kuival'], 1,
		'Halvim kombinatsioon on raske haagis kerge auto taga.'],
	['koorem', 'j', 'Haagisega kurvis pidurdamine. Mis on ohuks, mida pidurdusteekond ei näita?',
		['Ohtu pole', 'Haagis võib hakata loksuma või auto „kokku voltida“', 'Haagis tuleb lahti', 'Mootor seiskub'], 1,
		'Pidurita haagis lükkab autot tagant ka külje suunas. Pidurda haagisega enne kurvi ja sujuvalt.', SIM.kurv()],
	['koorem', 'j', 'Kuidas paigutada raske koorem haagisesse?',
		['Taha', 'Telje kohale ja madalale, natuke ette, et aisale tuleks soovitatud koormus', 'Üles, et oleks näha', 'Vahet pole'], 1,
		'Tagumine koorem võtab aisalt koormuse ära ja haagis hakkab loksuma.'],
	['koorem', 'e', 'Lähed pikale sõidule: autos on viis inimest ja pagasiruum on asju täis. Mida rehvidega enne teha?',
		['Mitte midagi', 'Kontrollida rõhku: suure koormaga soovitab tootja enamasti suuremat rõhku', 'Lasta õhku välja, et haare oleks parem', 'Vahetada talverehvid'], 1,
		'Koormatud auto rõhutabel on tavaliselt juhiukse piilaril või kütusepaagi luugil.'],

	/* ---------- 9. reeglid ---------- */
	['reeglid', 'e', 'Millal on talverehvid Eestis kohustuslikud?',
		['1. novembrist 1. aprillini', '1. detsembrist 1. märtsini', 'Kogu talve, kui on lumi', 'Ei ole kohustuslikud'], 1,
		'Varem võib panna, ja tasub panna, kui tuleb esimene külm.'],
	['reeglid', 'e', 'Millal on naastrehvid lubatud?',
		['Ainult 1. detsembrist 1. märtsini', '15. oktoobrist 31. märtsini; talviste olude korral 1. oktoobrist 30. aprillini', 'Aastaringselt', 'Ainult maanteel'], 1,
		'Lamellrehvidega võib sõita aastaringselt.'],
	['reeglid', 'e', 'Mis on talverehvi minimaalne mustrisügavus?',
		['1,6 mm', '2 mm', '3 mm', '5 mm'], 2,
		'Lumel on 3 mm mustriga pidurdusteekond juba umbes veerandi võrra pikem kui uuel.', SIM.mang('tuled', 'kiirus=50&ilm=talv&mm=3')],
	['reeglid', 'jt', 'Suverehvi minimaalne muster on 1,6 mm. Mida tähendab see ohutuse kohta?',
		['1,6 mm on ohutu, sest seadus lubab', 'See on miinimum, mitte ohutu tase: märjal ja vees pikeneb pidurdus selgelt juba 3 mm juures', '1,6 mm on parim, rehv on kerge', 'Mustril pole suvel tähtsust'], 1,
		'90 km/h, 3 mm veekiht: uus rehv 54 m, 3 mm 70 m, 1,6 mm 101 m.', SIM.peatumine('kiirus=90&vesi=3', 'kiirus=90&vesi=3&muster=3')],
	['reeglid', 'jt', 'Milline märgis peab olema talverehvil?',
		['Ainult M+S', 'Kolm mäetippu ja lumehelves', 'EL-i rehvimärgis A-klass', 'Märgist pole vaja'], 1,
		'Alates 1. detsembrist 2022 ei sobi Eestis talverehviks Kesk-Euroopa pehme talve rehvid. M+S üksi ei näita talvehaaret.'],
	['reeglid', 'jt', 'Kas helkur on kohustuslik ka valgustatud linnatänaval?',
		['Ei, ainult maal', 'Jah, pimedal ajal teel liikudes', 'Ainult lastel', 'Ainult udu korral'], 1,
		'Helkuri kohustus kehtib pimeda ajal ja halva nähtavuse korral.'],
	['reeglid', 'j', 'Kas seadus ütleb pikivahe sekundites?',
		['Jah, täpselt 2 sekundit', 'Ei: vahe peab olema selline, et jõuad peatuda, kui eesolev auto pidurdab; 2–3 s on rusikareegel', 'Jah, 3 autopikkust', 'Pikivahet ei reguleerita'], 1,
		'Libedal teel ja väsinult on vaja rohkem.', SIM.pikivahe()]
];

/* id = teema + järjekorranumber teemas: uued küsimused lisa teema LÕPPU, et nähtud küsimuste märge ei nihkuks */
const loendur = {};
const POHI = K.map(([teema, m, k, v, o, s, sim]) => ({ id: teema + '-' + (loendur[teema] = (loendur[teema] || 0) + 1), teema, m, k, v, o, s, sim: sim || null }));

/* kaksiku oma simulaatori olukord (sama mis kaksiku arvudes); puudub → põhiküsimuse oma */
const PAAR_SIM = {
	'kiirus-1': SIM.peatumine('kiirus=30', 'kiirus=60'),
	'kiirus-3': SIM.mang('tuled', 'kiirus=70&ilm=kuiv'),
	'kiirus-4': SIM.peatumine(KUIV + '&kiirus=80', KUIV + '&kiirus=90'),
	'kiirus-5': SIM.peatumine(KUIV + '&kiirus=50', KUIV + '&kiirus=70'),
	'kiirus-7': SIM.mang('tuled', 'kiirus=70&ilm=vihm'),
	'kiirus-8': SIM.peatumine(KUIV + '&kiirus=50', KUIV + '&kiirus=60'),
	'kiirus-10': SIM.peatumine('kiirus=90', 'kiirus=90&kalle=6'),
	'reaktsioon-1': SIM.mang('tuled', 'kiirus=50&ilm=kuiv'),
	'reaktsioon-3': SIM.peatumine('kiirus=90', 'kiirus=90&reakt=3'),
	'reaktsioon-4': SIM.peatumine(KUIV + '&kiirus=50&takistus=24', KUIV + '&kiirus=50&reakt=1.5'),
	'reaktsioon-6': SIM.peatumine('kiirus=30&reakt=2', 'kiirus=90&reakt=2'),
	'reaktsioon-7': SIM.peatumine('kiirus=50', 'kiirus=50&reakt=1.5'),
	'teeolud-1': SIM.peatumine(KUIV + '&kiirus=30', LUMI + '&kiirus=30'),
	'teeolud-2': SIM.peatumine(JAA + '&kiirus=30'),
	'teeolud-6': SIM.peatumine('kiirus=90&vesi=3', 'kiirus=90&vesi=3&muster=3'),
	'teeolud-8': SIM.peatumine(LUMI + '&kiirus=30', 'pind=SNOW_LOOSE&vesi=0&temp=-5&kat=WINTER_NORDIC&kiirus=30'),
	'teeolud-9': SIM.peatumine('kiirus=50', 'kiirus=50&kat=WINTER_NORDIC'),
	'rehvid-1': SIM.peatumine(JAA + '&kiirus=50', 'pind=ICE&vesi=0&temp=-5&kat=SUMMER_TOURING&kiirus=50'),
	'rehvid-2': SIM.peatumine(KUIV + '&kiirus=90', KUIV + '&kiirus=90&kat=WINTER_NORDIC'),
	'rehvid-3': SIM.peatumine('kiirus=90', 'kiirus=90&muster=3'),
	'rehvid-4': SIM.mang('tuled', 'kiirus=50&ilm=talv&mm=4'),
	'rehvid-5': SIM.peatumine('kiirus=90', 'kiirus=90&vanus=6'),
	'rehvid-10': SIM.peatumine(KUIV + '&kiirus=50&kat=WINTER_STUDDED', KUIV + '&kiirus=50&kat=WINTER_NORDIC'),
	'rehvid-11': SIM.peatumine(JAA + '&kiirus=50', 'pind=ICE&vesi=0&temp=-5&kat=WINTER_CENTRAL&kiirus=50'),
	'pikivahe-2': SIM.mang('tuled', 'kiirus=90&vahe=0.5&ilm=kuiv'),
	'pikivahe-4': SIM.pikivahe('vahe=2&kiirus=50'),
	'pikivahe-5': SIM.pikivahe('vahe=3&kiirus=90'),
	'pikivahe-8': SIM.pikivahe('vahe=3&kiirus=90'),
	'pimedus-2': SIM.mang('pime', 'riie=tume&kiirus=60&ilm=kuiv'),
	'pimedus-3': SIM.mang('pime', 'riie=tume&kiirus=90&ilm=vihm'),
	'pimedus-4': SIM.mang('pime', 'riie=helkur&kiirus=130&ilm=vihm'),
	'pimedus-9': SIM.peatumine('kiirus=70&takistus=50'),
	'kurvid-2': SIM.kurv('kr=50~lumi~WINTER_NORDIC~8~8~vw_passat_b8'),
	'kurvid-6': SIM.kurv('kr=60~marg~SUMMER_TOURING~2~8~vw_golf_3'),
	'koorem-1': SIM.peatumine(KUIV + '&kiirus=80', KUIV + '&kiirus=80&laad=375'),
	'koorem-2': SIM.peatumine(KUIV + '&kiirus=80', KUIV + '&kiirus=80&haagis=pidurita&haagisKg=750'),
	'reeglid-3': SIM.mang('tuled', 'kiirus=50&ilm=talv&mm=2.5'),
	'reeglid-4': SIM.peatumine('kiirus=90&vesi=3', 'kiirus=90&vesi=3&muster=2')
};

/* kaksik: sama teadmine teises olukorras (lib/koolitus/paarid.js), id = põhiküsimuse id + 'b' */
import { PAARID } from './paarid.js';
export const KYSIMUSED = POHI.map((q) => {
	const p = PAARID[q.id];
	return { ...q, paar: p ? { id: q.id + 'b', teema: q.teema, m: q.m, k: p[0], v: p[1], o: p[2], s: p[3], sim: p[4] || PAAR_SIM[q.id] || q.sim } : null };
});
/* id → küsimus (ka kaksikud), õpetaja vaate jaoks; teema = põhiküsimuse id (kaksikutel ilma b-ta) */
const KOIK = new Map();
for (const q of KYSIMUSED) { KOIK.set(q.id, q); if (q.paar) KOIK.set(q.paar.id, q.paar); }
export const leiaKysimus = (id) => KOIK.get(id) || null;
export const pohiId = (id) => String(id).replace(/b$/, '');
