/* Iga küsimuse „kaksik“: kontrollib SAMA teadmist teise olukorra või sõnastusega.
 * Eeltestis tuleb üks, järeltestis teine (juhuslikult kumb), nii et enne/pärast võrdlus
 * näitab, kas just see asi sai selgemaks. Arvud samast mudelist (Golf 8, C-klassi rehv,
 * kuiv +15 °C, märg 1 mm +10 °C, lumi/jää −5 °C, reaktsioon 1 s).
 * Kuju: id: [küsimus, [4 vastust], õige, selgitus, sim?]  (sim puudub → sama mis põhiküsimusel) */
export const PAARID = {
	/* ---------- kiirus ---------- */
	'kiirus-1': ['Märg tee. Kiirus kasvab 30-lt 60 km/h peale. Kuidas muutub pidurdusteekond?',
		['Kaks korda pikem', 'Umbes neli korda pikem', 'Pool pikem', 'Ei muutu'], 1,
		'Kiirus kahekordistub, pidurdusteekond kasvab kiiruse ruuduga: 5,1 m → 19,5 m.'],
	'kiirus-2': ['Juht märkab ohtu ja vajutab pidurit alles 1 sekundi pärast. Kuhu kuulub see 1 sekundi jooksul sõidetud teekond?',
		['Pidurdusteekonda', 'Peatumisteekonda: see on reaktsiooni osa', 'Mitte kuhugi, siis auto veel ei pidurda', 'Ainult siis, kui tee on märg'], 1,
		'Peatumisteekond = reaktsiooni teekond + pidurdusteekond. Reaktsiooni ajal sõidab auto täiskiirusel.'],
	'kiirus-3': ['Kuiv tee, 70 km/h, reageerid 1 sekundiga. Kui pikk on peatumisteekond?',
		['Umbes 18 m', 'Umbes 25 m', 'Umbes 38 m', 'Umbes 70 m'], 2,
		'19,4 m reaktsioon + 18,3 m pidurdus = 37,7 m.'],
	'kiirus-4': ['Kuiv tee. Kõrvalrajal sinuga kõrvuti sõitev auto sõidab 80 km/h, sina 90 km/h. Mõlemad pidurdavad sama takistuse pärast. Kui tema seisab, mis kiirusega oled sina samas kohas?',
		['Ka seisad', 'Umbes 10 km/h', 'Umbes 30 km/h', 'Umbes 50 km/h'], 3,
		'Ainult 10 km/h rohkem, aga samas kohas on sul veel 51 km/h. Lisakiirus jääb pidurdusteekonna lõppu.'],
	'kiirus-5': ['Kuiv tee, 50 km/h ala. Üks auto sõidab 50 km/h, teine 70 km/h. Kohas, kus esimene jõuab seisma, sõidab teine veel…',
		['5 km/h', '25 km/h', '45 km/h', '65 km/h'], 3,
		'Kuival teel 1 s reaktsiooniga: esimene peatub 23,5 m pärast, teine on seal veel 65 km/h.'],
	'kiirus-6': ['Mis on ABS-i peamine kasu äkkpidurdusel?',
		['Pidurdusteekond on alati poole lühem', 'Saad pidurdades rooli keerata ja takistusest mööda juhtida', 'Auto ei libise kunagi', 'Pidurid ei kuumene'], 1,
		'ABS hoiab rattad pöörlemas. Lukus ratas ei juhi, pöörlev juhib.'],
	'kiirus-7': ['70 km/h pealt märjal teel: kui pikk on pidurdusteekond (pidurdamise algusest)?',
		['Umbes 12 m', 'Umbes 27 m', 'Umbes 45 m', 'Umbes 70 m'], 1,
		'Pidurdusteekond on ainult pidurdamise algusest seisuni: mudelis 26,6 m. Umbes 45 m (mudelis 46,0 m) on peatumisteekond: sinna kuulub ka 1 s reaktsiooni ajal sõidetud 19,4 m.'],
	'kiirus-8': ['Kiirus kasvab 50-lt 60 km/h peale (+20%). Kui palju kasvab pidurdusteekond kuival?',
		['Samuti 20%', 'Umbes 40%', 'Kaks korda', 'Ei muutu'], 1,
		'9,6 m → 13,6 m, ehk +42%. Pidurdusteekond kasvab kiirusest kiiremini.'],
	'kiirus-9': ['Mis mõjutab pidurdusteekonda kõige vähem?',
		['Märg tee kuiva asemel', '20 km/h suurem kiirus', 'Kulunud rehvid', 'Kaks reisijat tagaistmel'], 3,
		'Kaks reisijat lisab pidurdusteekonnale alla meetri. Kõik teised muudavad seda mitu meetrit.'],
	'kiirus-10': ['Ülesmäge 6% tõus, märg tee, 90 km/h. Kuidas muutub pidurdusteekond võrreldes tasase teega?',
		['Lüheneb umbes 3 m', 'Pikeneb umbes 3 m', 'Ei muutu', 'Pikeneb kaks korda'], 0,
		'Tõusul aitab raskusjõud pidurdada: 44,8 m → 41,5 m. Allamäge on vastupidi: 48,8 m.'],

	/* ---------- reaktsioon ---------- */
	'reaktsioon-1': ['Kui palju sõidab auto 50 km/h juures 1 sekundiga?',
		['5 m', 'Umbes 14 m', '25 m', '50 m'], 1,
		'50 km/h = 13,9 m/s. Linnas on see umbes kolm autopikkust iga sekund.'],
	'reaktsioon-2': ['Väsinud juht, ootamatu oht. Mis on realistlik reaktsiooniaeg?',
		['0,3 s', '0,5 s', '1,5–2 s või rohkem', 'Alati täpselt 1 s'], 2,
		'Puhanud ja valmis juht reageerib umbes 1 sekundiga, väsinud või hajevil juht tunduvalt aeglasemalt.'],
	'reaktsioon-3': ['Vaatad 90 km/h juures 3 sekundit telefoni. Kui palju sõidad pimesi?',
		['Umbes 25 m', 'Umbes 50 m', 'Umbes 75 m', 'Umbes 150 m'], 2,
		'25 m/s × 3 s = 75 m. See on rohkem kui terve jalgpalliväljaku pool.'],
	'reaktsioon-4': ['Kuiv tee, 50 km/h, takistus 24 m ees. 1 s reaktsiooniga jõuad napilt peatuda. Mis juhtub, kui reageerid 1,5 s?',
		['Peatud ikka napilt', 'Peatud 5 m varem', 'Sõidad otsa umbes 44 km/h kiirusega', 'Auto peatub ise'], 2,
		'Pool sekundit lisab 7 m täiskiirusel sõitu. Pidurdamiseks jääb nii vähe ruumi, et kiirus jõuab vaevu langeda.'],
	'reaktsioon-5': ['Ees seisab bussipeatuses buss. Mis aitab kõige rohkem, kui keegi peaks bussi eest välja astuma?',
		['Kiirendada, et bussist kiiresti mööda saada', 'Jalg gaasilt ja pidurivalmis, kiirus maha', 'Signaal anda', 'Vahet pole, reaktsioon on sama'], 1,
		'Kui oled ohuks valmis, jääb ära otsustamise aeg ja peatumisteekond lüheneb mitu meetrit.'],
	'reaktsioon-6': ['Telefon lisab 1 sekundi reaktsiooniaega. Mitu meetrit lisab see 30 ja 90 km/h juures?',
		['Mõlemal 10 m', 'Umbes 8 m ja 25 m', 'Umbes 3 m ja 9 m', 'Umbes 8 m ja 75 m'], 1,
		'Reaktsiooni teekond kasvab kiirusega otse: 8,3 m ja 25 m.'],
	'reaktsioon-7': ['Väsinud juht reageerib 0,5 s aeglasemalt. Kui palju lisab see 50 km/h juures?',
		['Umbes 1 m', 'Umbes 7 m', 'Umbes 14 m', 'Umbes 25 m'], 1,
		'13,9 m/s × 0,5 s ≈ 7 m. Linnas on see ülekäiguraja laius.'],
	'reaktsioon-8': ['Sõber sai reaktsioonimängus 0,3 s. Mis on tema kohta õige?',
		['Liikluses reageerib ta samuti 0,3 s', 'Liikluses on ta aeglasem, sest seal ei tea ta ette, millal oht tuleb', 'Ta ei pea pikivahet hoidma', 'Tema peatumisteekond on alati lühike'], 1,
		'Mängus ootad ohtu. Liikluses lisandub märkamine ja otsustamine.'],
	'reaktsioon-9': ['Mis on roolis kõige ohtlikum?',
		['Raadiojaama vahetamine nupuga', 'Telefonist sõnumi lugemine', 'Peeglisse vaatamine', 'Rooli kahe käega hoidmine'], 1,
		'Sõnumit lugedes on pilk mitu sekundit teelt ja mõte mujal. 90 km/h juures on 2 sekundit 50 m pimesi.'],

	/* ---------- teeolud ---------- */
	'teeolud-1': ['30 km/h. Mitu korda pikem on pidurdusteekond tallatud lumel (talverehviga) kui kuival asfaldil?',
		['Sama', 'Umbes 1,2 korda', 'Umbes 2,5 korda', 'Umbes 10 korda'], 2,
		'Kuival 3,7 m, lumel 9,6 m. Ka aeglaselt sõites on vahe suur.'],
	'teeolud-2': ['30 km/h, jää, Põhjamaade lamellrehv. Kui pikk on pidurdusteekond?',
		['Umbes 4 m', 'Umbes 14 m', 'Umbes 30 m', 'Umbes 50 m'], 1,
		'Mudelis 14,3 m. Kuival asfaldil oleks 3,7 m.'],
	'teeolud-3': ['Öösel oli −3 °C, päeval tõuseb nulli. Tee on jäine. Millal on see kõige libedam?',
		['Öösel kõige külmemal ajal', 'Nulli lähedal, kui jää pind hakkab sulama', 'Alati ühtemoodi', 'Kui päike paistab'], 1,
		'Jää pinnal olev õhuke vesi teeb sellest kõige libedama. Mudelis 0 °C juures 58,6 m, −15 °C juures 27,4 m (50 km/h).'],
	'teeolud-4': ['Auto termomeeter näitab +3 °C. Kus on kõige tõenäolisemalt jää?',
		['Mitte kuskil', 'Sillal ja metsavarjus olevatel lõikudel', 'Ainult ristmikel', 'Ainult kruusateel'], 1,
		'Sild jahtub ka altpoolt ja varjus ei sula jää. Termomeeter mõõdab õhku, mitte teed.'],
	'teeolud-5': ['Sõidad läbi sügava lombi ja rool läheb äkki kergeks. Mis toimub?',
		['Roolivõimendi läks rikki', 'Rehvid ujuvad vee peal ega puuduta teed', 'Pidurid on märjad', 'Auto pidurdab ise'], 1,
		'See on vesiliug. Kuni rehv ei puuduta teed, ei mõju ei rool ega pidurid.'],
	'teeolud-6': ['90 km/h, 3 mm veekiht. Kui palju pikem on pidurdusteekond 3 mm mustriga suverehviga kui uuega?',
		['Alla meetri', 'Umbes 16 m', 'Umbes 50 m', 'Ei muutu'], 1,
		'53,8 m → 70,3 m. Mida õhem muster, seda vähem vett jõuab rehv eest ära juhtida.'],
	'teeolud-7': ['Auto hakkab vee peal ujuma. Mis on kõige halvem, mida teha?',
		['Gaas ära võtta', 'Rool otse hoida', 'Järsult pidurdada ja rooli keerata', 'Oodata, kuni rehvid haarduvad'], 2,
		'Kui rehvid haarduvad uuesti viltu keeratud rooliga, võib auto külje peale visata.'],
	'teeolud-8': ['30 km/h, talverehvid. Kus peatud lühemalt: tallatud või kohevas lumes?',
		['Kohevas lumes', 'Tallatud lumel', 'Sama', 'Kohevas lumes ei saa üldse peatuda'], 1,
		'Mudelis 9,6 m tallatud ja 11,1 m kohevas lumes.'],
	'teeolud-9': ['Märg asfalt, +10 °C, 50 km/h. Kumb peatub lühemalt: suverehv või talverehv?',
		['Talverehv, sest haarab paremini', 'Suverehv: 13,5 m vs 13,8 m', 'Täpselt sama', 'Talverehv kaks korda lühemalt'], 1,
		'Plusskraadidel märjal asfaldil on suverehv parem. Talverehvi eelis on lumel ja jääl.'],
	'teeolud-10': ['Pärast kahte kuivat nädalat hakkab sadama. Millal on tee kõige libedam?',
		['Pärast tundi vihma', 'Esimestel minutitel, kui tolm ja õli tõusevad veega pinnale', 'Alles õhtul', 'Vihm teeb tee alati sama libedaks'], 1,
		'Esimene vihm segab tee mustuse libedaks kihiks. Pikem vihm uhub selle ära.'],

	/* ---------- rehvid ---------- */
	'rehvid-1': ['Jää, 50 km/h. Kui palju pikem on pidurdusteekond suverehviga kui Põhjamaade talverehviga?',
		['Sama', 'Umbes 10%', 'Üle kahe korra: 39 m → 83 m', 'Suverehv peatub lühemalt'], 2,
		'Suverehvi kumm kõvastub külmaga ega haara jääd.'],
	'rehvid-2': ['Suvi, kuiv asfalt, 90 km/h. Kui palju pikem on pidurdusteekond, kui all on talverehvid?',
		['Lühem', 'Sama', 'Umbes 10 m pikem: 29,8 m → 39,7 m', 'Kaks korda pikem'], 2,
		'Talverehv on soojal asfaldil pehme ja lamellid painduvad.'],
	'rehvid-3': ['Suverehvi muster on 3 mm. Kui palju pikem on pidurdusteekond märjal 90 km/h pealt kui uuel rehvil?',
		['Ei muutu', 'Umbes 4 m: 44,8 m → 49,0 m', 'Umbes 20 m', 'Kaks korda'], 1,
		'Muster juhib vee eest ära. Iga kulunud millimeeter lisab märjal meetreid.'],
	'rehvid-4': ['Talverehvi muster on 4 mm (seaduslik). Kui palju pikem on pidurdusteekond lumel 50 km/h pealt kui uuel?',
		['Ei muutu', 'Umbes 5 m: 26,2 m → 31,1 m', 'Umbes 20 m', 'Lühem'], 1,
		'Lumel haarab muster lund. Juba 4 mm juures on pidurdus selgelt pikem.'],
	'rehvid-5': ['Rehv on 6 aastat vana, muster täis. Kui palju pikeneb pidurdusteekond märjal 90 km/h pealt?',
		['Alla meetri', 'Umbes 5 m', 'Umbes 10 m', 'Kaks korda'], 0,
		'Mudelis 44,8 m → 45,2 m. Vanus mõjub vähem kui muster, 10-aastasel on vahe juba 2,4 m.'],
	'rehvid-6': ['Rehvi DOT-kood lõpeb numbritega 0819. Millal on rehv tehtud?',
		['8. augustil 2019', '2019. aasta 8. nädalal', '2008. aastal', '19. augustil'], 1,
		'Kaks esimest numbrit on nädal, kaks viimast aasta.'],
	'rehvid-7': ['Mis näitab EL-i rehvimärgisel, kui hästi rehv märjal pidurdab?',
		['Müratase dB', 'Märghaarde klass A–E', 'Kütusesäästu klass', 'Lumehelbe märk'], 1,
		'A ja E klassi vahe on märjal 90 km/h pealt umbes 18 m.'],
	'rehvid-8': ['Rehvirõhk on liiga madal. Mis juhtub sügavas vees?',
		['Vesiliug algab madalamal kiirusel', 'Vesiliugu ei teki', 'Haare paraneb', 'Midagi ei muutu'], 0,
		'Pehme rehv ei suru vett mustrist välja. Liiga madala rõhuga algab vesiliug mitukümmend km/h varem.'],
	'rehvid-9': ['Ilm läheb 10 kraadi külmemaks. Kuidas muutub rehvirõhk?',
		['Ei muutu', 'Langeb umbes 0,1 bar', 'Tõuseb 0,1 bar', 'Langeb 1 bar'], 1,
		'Umbes 0,1 bar iga 10 kraadi kohta. Kontrolli rõhku, kui ilm külmeneb.'],
	'rehvid-10': ['Kuiv asfalt, 50 km/h. Naastrehv või lamellrehv: kumb peatub lühemalt?',
		['Naastrehv tunduvalt lühemalt', 'Lamell tunduvalt lühemalt', 'Vahe on väike: 12,9 m vs 12,7 m', 'Naastrehviga ei tohi asfaldil sõita'], 2,
		'Naastude eelis on jääl. Asfaldil on vahe väike.'],
	'rehvid-11': ['Kesk-Euroopa talverehv (pehmete talvede jaoks) jääl 50 km/h pealt. Mis on õige?',
		['Sama hea kui Põhjamaade rehv', 'Palju halvem: 64 m vs 39 m', 'Parem kui naastrehv', 'Sama halb kui suverehv'], 1,
		'Selline rehv on tehtud lörtsi ja märja jaoks, mitte jää jaoks. Eesti talves on Põhjamaade rehv jääl tunduvalt parem.'],
	'rehvid-12': ['Ostad esiveolisele autole ainult kaks uut rehvi. Kuhu need panna?',
		['Ette, sest ees on vedavad rattad', 'Taha, et auto tagaosa ei libiseks kurvis välja', 'Üks ette, üks taha', 'Vahet pole'], 1,
		'Libisevat esiotsa on lihtsam kontrollida kui libisevat tagaotsa.'],

	/* ---------- pikivahe ---------- */
	'pikivahe-1': ['Mis on 2-sekundilise reegli mõte?',
		['Kaks auto pikkust vahet', 'Vahe kasvab kiirusega ise kaasa ja katab reaktsiooniaja', 'Kaks sekundit pärast pidurdamist peab auto seisma', 'See kehtib ainult linnas'], 1,
		'Sekundites mõõdetud vahe on 50 km/h juures 28 m ja 90 km/h juures 50 m.'],
	'pikivahe-2': ['Pikivahe on 0,5 sekundit ja sina reageerid 1 sekundiga. Eesolev auto pidurdab järsult. Mis juhtub?',
		['Peatud napilt', 'Kokkupõrge, sest reaktsioon on pikem kui vahe', 'ABS päästab', 'Eesolev auto peatub aeglasemalt'], 1,
		'Kui mõlemad pidurdavad sama hästi, peab pikivahe olema vähemalt reaktsiooniaja pikkune.'],
	'pikivahe-3': ['Lumine tee. Ees sõidab naastrehvidega auto, sinul on lamellrehvid. Kas 2 sekundit vahet piisab?',
		['Piisab alati', 'Ei pruugi: tema peatub kiiremini, võta suurem vahe', 'Lumel piisab 1 sekundist', 'Rehvid ei loe'], 1,
		'Kui eesolev auto pidurdab paremini, kulub sinu varu kiiresti ära. Libedal on see vahe meetrites suur.'],
	'pikivahe-4': ['Mitu meetrit on 2-sekundiline pikivahe 50 km/h juures?',
		['10 m', 'Umbes 28 m', '50 m', '100 m'], 1,
		'13,9 m/s × 2 s ≈ 28 m.'],
	'pikivahe-5': ['Pikivahe on 3 sekundit. Vaatad 1 sekund telefoni ja siis eesolev auto pidurdab. Mis on tõenäoline?',
		['Kokkupõrge on vältimatu', 'Jõuad peatuda, sest pilk + reaktsioon mahub 3 sekundi sisse', 'Pole vahet, kas vahe on 1 või 3 s', 'ABS teeb kõik ise'], 1,
		'1 s pilku + 1 s reaktsiooni = 2 s. 3 s vahe annab veel 1 s varu.'],
	'pikivahe-6': ['Kolonnis sõidab sinu ees auto 1-sekundilise vahega. Mida teha?',
		['Jääda nii', 'Võtta vahe vähemalt 2 sekundi peale', 'Möödasõit kohe', 'Tulesid vilgutada'], 1,
		'1 sekund ei kata isegi tavalist reaktsiooniaega.'],
	'pikivahe-7': ['Tagumine auto sõidab liiga lähedal ja ees on fooris punane tuli. Mis on parim?',
		['Pidurdada viimasel hetkel', 'Pidurdada varakult ja sujuvalt', 'Kiirendada ja kollasega üle sõita', 'Ohutuled sisse'], 1,
		'Varajane ja sujuv pidurdus annab tagumisele juhile aega reageerida.'],
	'pikivahe-8': ['Mitu meetrit on 3-sekundiline pikivahe 90 km/h juures?',
		['Umbes 30 m', 'Umbes 50 m', 'Umbes 75 m', 'Umbes 150 m'], 2,
		'25 m/s × 3 s = 75 m.'],

	/* ---------- pimedus ---------- */
	'pimedus-1': ['Mitu korda kaugemalt paistab lähitulede valgel helkuriga jalakäija kui tumedas riietes helkurita jalakäija?',
		['Sama kaugelt', 'Umbes 1,5 korda', 'Umbes 4–5 korda', 'Umbes 50 korda'], 2,
		'Tumedas riietes umbes 30 m, helkuriga 130–150 m (Transpordiamet).'],
	'pimedus-2': ['Kuiv tee, pime. Tumedas riietes jalakäija ilmub 30 m ette, sina reageerid 1 sekundiga. Mis kiiruselt jõuad veel peatuda?',
		['Umbes 40 km/h', 'Umbes 59 km/h', 'Umbes 80 km/h', 'Umbes 100 km/h'], 1,
		'Kuival teel kuni 59 km/h, märjal ainult 53 km/h. Kiiremini sõites jõuab auto jalakäijani.'],
	'pimedus-3': ['Pime maantee, märg asfalt, 90 km/h. Tumedas riietes jalakäija ilmub 30 m ette. Mis kiirusega jõuab auto jalakäijani?',
		['Peatub enne', 'Umbes 40 km/h', 'Umbes 87 km/h', '120 km/h'], 2,
		'1 sekundiga sõidab auto 25 m. Pidurdamiseks jääb 5 m ja kiirus jõuab vaevu langeda.'],
	'pimedus-4': ['Helkuriga jalakäija paistab 140 m kauguselt. Märg tee, reaktsioon 1 s. Mis kiiruselt jõuad veel peatuda?',
		['Umbes 50 km/h', 'Umbes 80 km/h', 'Umbes 130 km/h', 'Igalt kiiruselt'], 2,
		'Mudelis kuni 132 km/h. Ilma helkurita (30 m) ainult 53 km/h.'],
	'pimedus-5': ['Lapse helkur ripub seljakoti küljes õla kõrgusel. Kas see on hea koht?',
		['Jah, seal on see kõige paremini näha', 'Parem on 50–80 cm kõrgusel, sõidutee poolsel küljel', 'Helkur peab olema mütsil', 'Koht ei loe'], 1,
		'Lähitulede valgus on madal. Õla kõrgusel jääb helkur valgusest välja või keha varju.'],
	'pimedus-6': ['Vihmane hämar pärastlõuna, veel ei ole päris pime. Kas helkur peab olema?',
		['Ei, alles pimedas', 'Jah, ka halva nähtavuse korral', 'Ainult maanteel', 'Ainult lastel'], 1,
		'Helkur on kohustuslik pimeda ajal ja halva nähtavuse korral.'],
	'pimedus-7': ['Kumb teeb jalakäija pimedas paremini nähtavaks: valge jope või väike helkur?',
		['Valge jope', 'Helkur: hele riie paistab 40–50 m, helkur 130–150 m', 'Sama', 'Kumbki ei aita'], 1,
		'Helkur peegeldab valguse tagasi juhi poole.'],
	'pimedus-8': ['Vastutulija ei lülita kaugtulesid välja ja sind pimestab. Mida teha?',
		['Vaadata tuledesse, et näha, kus ta on', 'Vaadata oma raja paremasse serva ja kiirust vähendada', 'Panna samuti kaugtuled', 'Sulgeda silmad'], 1,
		'Pimestatud juht ei näe teeäärt, kus võib olla helkurita jalakäija.'],
	'pimedus-9': ['Udu, näed umbes 50 m kaugusele. Tee on märg, reaktsioon 1 s. Milline kiirus on veel ohutu?',
		['Umbes 70 km/h', 'Umbes 90 km/h', 'Umbes 110 km/h', 'Piirkiirus'], 0,
		'Märjal 70 km/h pealt on peatumisteekond 46 m, 80 km/h pealt juba 57 m.'],

	/* ---------- kurvid ---------- */
	'kurvid-1': ['Kiirus kurvis kasvab 60-lt 90 km/h peale (1,5 korda). Kuidas muutub jõud, mis autot kurvist välja lükkab?',
		['1,5 korda', 'Umbes 2,25 korda', '3 korda', 'Ei muutu'], 1,
		'Külgjõud kasvab kiiruse ruuduga: 1,5 × 1,5 = 2,25.'],
	'kurvid-2': ['100 m raadiusega kurv, kuival piirkiirus umbes 120 km/h. Mis on see tallatud lumel (talverehviga)?',
		['Umbes 110 km/h', 'Umbes 70 km/h', 'Umbes 30 km/h', 'Sama'], 1,
		'Lumel on haaret umbes kolmandik kuivast. Piirkiirus kasvab haarde ruutjuurega.'],
	'kurvid-3': ['Miks läheb auto kurvis pidurdades kergemini libisema kui otse sõites?',
		['Pidurid töötavad kurvis halvemini', 'Rehvi haaret kulub juba pööramisele ja pidurdamiseks jääb vähem', 'ABS lülitub kurvis välja', 'Ei lähe'], 1,
		'Rehvil on üks haarde „kott“. Mida rohkem kulub pööramisele, seda vähem jääb pidurdamiseks.'],
	'kurvid-4': ['Ees on järsu kurvi märk. Millal kiirust vähendada?',
		['Kurvi tipus', 'Enne kurvi, kui auto sõidab veel otse', 'Kurvist väljudes', 'Ei peagi, kui on ABS'], 1,
		'Otse sõites saab kogu haarde pidurdamiseks kasutada.'],
	'kurvid-5': ['ABS-ita auto, esirattad lukus. Mis juhtub, kui keerad rooli?',
		['Auto pöörab', 'Auto sõidab edasi otse', 'Auto pöörab vastassuunas', 'Rattad hakkavad ise pöörlema'], 1,
		'Lukus ratas libiseb ega juhi. Rool hakkab mõjuma alles siis, kui ratas pöörleb.'],
	'kurvid-6': ['Märjas kurvis on esirehvid kulunud, tagumised uued. Mis juhtub tõenäoliselt?',
		['Tagaosa libiseb välja', 'Auto kipub otse sõitma ehk kurvist välja', 'Midagi ei juhtu', 'Auto pöörab paremini'], 1,
		'Kus on kehvemad rehvid, see auto ots libiseb esimesena. Ees tähendab see, et auto ei pööra.'],
	'kurvid-7': ['Kurvi piirkiirus on kuival umbes 120 km/h. Mis on see samas kurvis märjal?',
		['Sama', 'Umbes 100 km/h', 'Umbes 60 km/h', 'Umbes 30 km/h'], 1,
		'Märjal on haaret umbes kaks kolmandikku kuivast.'],
	'kurvid-8': ['Mida tähendab, et kurvis on „varu“?',
		['Auto on täis tangitud', 'Sa sõidad piirkiirusest piisavalt aeglasemalt, et ootamatus ei viiks teelt välja', 'Kurv on lai', 'Autol on varuratas'], 1,
		'Varu on kiirus, mille võrra oled kurvi piirkiirusest aeglasem. Seda läheb vaja jää või takistuse korral.'],

	/* ---------- koorem ---------- */
	'koorem-1': ['Kuiv tee, 80 km/h. Neli inimest ja pagas (375 kg) autos. Kui palju pikeneb pidurdusteekond?',
		['Alla meetri: 23,7 m → 24,1 m', 'Umbes 5 m', 'Poole võrra', 'Kaks korda'], 0,
		'Koorem pidurdusteekonda peaaegu ei muuda. Mõjutab rohkem juhitavust kurvis.'],
	'koorem-2': ['Kuiv tee, 80 km/h. Golfi taga 750 kg pidurita haagis. Kui pikk on pidurdusteekond?',
		['Sama, 24 m', 'Umbes 26 m', 'Umbes 35 m', 'Umbes 70 m'], 2,
		'Ilma haagiseta 23,7 m, pidurita haagisega 35,3 m.'],
	'koorem-3': ['1300 kg piduritega haagise pidurid ei tööta. Mis juhtub märjal 80 km/h pealt?',
		['Midagi, auto pidurid teevad töö', 'Pidurdusteekond on ligi kaks korda pikem: 65,0 m', 'Lüheneb, sest haagis on raske', 'Haagis pidurdab ise inertsiga'], 1,
		'Ilma haagiseta 35,0 m, töötavate piduritega 41,2 m, mitte töötavatega 65,0 m.'],
	'koorem-4': ['Haagise täismass on 900 kg. Kas see võib olla ilma oma piduriteta?',
		['Jah', 'Ei: ilma piduriteta lubatud kuni 750 kg', 'Jah, kui sõidad aeglaselt', 'Ainult suvel'], 1,
		'Täismass tähendab haagist koos koormaga.'],
	'koorem-5': ['Kerge väike auto ja raske pidurita haagis. Kuidas see kombinatsioon on?',
		['Hea, auto on kerge', 'Kõige halvem: haagis on auto massist suur osa', 'Vahet pole', 'Parem kui raske auto'], 1,
		'Mida suurem osa koguraskusest on pidurita haagis, seda rohkem pikeneb pidurdusteekond.'],
	'koorem-6': ['Haagis hakkab 80 km/h juures loksuma. Mida teha?',
		['Järsult pidurdada', 'Gaas sujuvalt ära, rool otse, järsult mitte pidurdada', 'Kiirendada', 'Rooli kiiresti vastu keerata'], 1,
		'Järsk pidurdus või rool võib loksumise hullemaks teha.'],
	'koorem-7': ['Haagis loksub juba 70 km/h juures. Mis on tõenäoline põhjus?',
		['Koorem on liiga ees', 'Koorem on liiga taga ja aisal on liiga vähe koormust', 'Rehvid on uued', 'Tee on kuiv'], 1,
		'Raske koorem käib telje kohale ja natuke ette.'],
	'koorem-8': ['Kust leiad õige rehvirõhu täis koormatud autole?',
		['Rehvi küljelt (maksimaalne rõhk)', 'Juhiukse piilarilt või kütusepaagi luugilt', 'Seda ei olegi', 'Bensiinijaama kompressorilt'], 1,
		'Rehvi küljel on maksimaalne lubatud rõhk, mitte auto jaoks õige rõhk.'],

	/* ---------- reeglid ---------- */
	'reeglid-1': ['On 15. detsember ja autol on suverehvid. Kas tohib sõita?',
		['Jah, kui lund ei ole', 'Ei: 1. detsembrist 1. märtsini on talverehvid kohustuslikud', 'Jah, linnas', 'Jah, kui sõidad aeglaselt'], 1,
		'Kohustus kehtib olenemata ilmast.'],
	'reeglid-2': ['On 20. aprill ja ilm on talvine. Kas naastrehvidega tohib sõita?',
		['Ei, ainult 31. märtsini', 'Jah, talviste olude korral kuni 30. aprillini', 'Jah, aastaringselt', 'Ainult maanteel'], 1,
		'Tavaliselt 15. oktoobrist 31. märtsini, talviste olude korral 1. oktoobrist 30. aprillini.'],
	'reeglid-3': ['Talverehvi muster on 2,5 mm. Kas see on lubatud?',
		['Jah', 'Ei: talverehvi muster peab olema sügavam kui 3 mm', 'Jah, kui rehv on uus', 'Ainult linnas'], 1,
		'Talverehvi nõue on üle 3 mm. Lumel on juba 3 mm juures pidurdus veerandi võrra pikem.'],
	'reeglid-4': ['Suverehvi muster on 2 mm. Mis on õige?',
		['See on seaduslik ja sama ohutu kui uus', 'See on seaduslik, aga märjal on pidurdus selgelt pikem', 'See on keelatud', 'Mustril pole suvel tähtsust'], 1,
		'Miinimum on 1,6 mm. Sademevee roopas on pidurdusteekond juba 3 mm juures palju pikem.'],
	'reeglid-5': ['Rehvil on ainult M+S märk. Kas see sobib Eestis talverehviks?',
		['Jah', 'Ei: vaja on kolme mäetipu ja lumehelbe märki', 'Jah, kui muster on üle 3 mm', 'Ainult naastudega'], 1,
		'M+S tähendab porisele ja lumisele teele sobivat mustrit, mitte talvist kummi.'],
	'reeglid-6': ['Kas helkur on kohustuslik ainult maal, kus tänavavalgustust pole?',
		['Jah', 'Ei: pimeda ajal ja halva nähtavuse korral igal pool teel', 'Ainult lastel', 'Ainult talvel'], 1,
		'Ka valgustatud tänaval võib juht olla pimestatud.'],
	'reeglid-7': ['Mida nõuab seadus pikivahe kohta?',
		['Täpselt 2 sekundit', 'Nii suurt vahet, et jõuad ohutult peatuda, kui eesolev pidurdab', '3 autopikkust', 'Midagi ei nõua'], 1,
		'2–3 sekundit on rusikareegel. Libedal teel ja väsinult on vaja rohkem.']
};
